package vfs

import (
	"fmt"
	"math/rand"
	"time"

	"github.com/spf13/afero"
)

func (s *SessionFS) populateLinux() {
	now := time.Now()

	// ─── Core directories ────────────────────────────────────────────
	dirs := []string{
		"/bin", "/sbin", "/usr/bin", "/usr/sbin", "/usr/local/bin",
		"/etc", "/etc/ssh", "/etc/apt", "/etc/cron.d", "/etc/default",
		"/etc/logrotate.d", "/etc/NetworkManager", "/etc/systemd/system",
		"/etc/security", "/etc/pam.d", "/etc/ssl/certs",
		"/var/log", "/var/log/journal", "/var/tmp", "/var/run",
		"/var/spool/cron/crontabs", "/var/cache/apt/archives",
		"/var/lib/dpkg", "/var/lib/apt/lists",
		"/tmp",
		"/root", "/root/.ssh",
		"/home", fmt.Sprintf("/home/%s", s.Username), fmt.Sprintf("/home/%s/.ssh", s.Username),
		fmt.Sprintf("/home/%s/Documents", s.Username), fmt.Sprintf("/home/%s/Downloads", s.Username),
		fmt.Sprintf("/home/%s/.local/share", s.Username),
		"/opt", "/srv",
		"/proc", "/proc/self",
		"/sys/class/net",
		"/dev",
		"/run/systemd",
		"/usr/share/doc", "/usr/share/man",
	}
	for _, d := range dirs {
		s.Fs.MkdirAll(d, 0755)
	}

	// ─── /etc ────────────────────────────────────────────────────────
	writeFile(s, "/etc/hostname", s.Hostname+"\n")
	writeFile(s, "/etc/os-release", fmt.Sprintf(`NAME="Ubuntu"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 22.04.3 LTS"
VERSION_ID="22.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
`))
	writeFile(s, "/etc/issue", "Ubuntu 22.04.3 LTS \\n \\l\n\n")
	writeFile(s, "/etc/issue.net", "Ubuntu 22.04.3 LTS\n")
	writeFile(s, "/etc/motd", fmt.Sprintf(`  System information as of %s

  System load:           0.%02d
  Usage of /:            %d%% of 49.12GB
  Memory usage:          %d%%
  Swap usage:            0%%
  Processes:             %d
  Users logged in:       %d
  IPv4 address for eth0: %s
`,
		now.Format("Mon Jan 2 15:04:05 MST 2006"),
		rand.Intn(99), 20+rand.Intn(60), 30+rand.Intn(50),
		100+rand.Intn(200), 1+rand.Intn(3), s.IP))

	writeFile(s, "/etc/passwd", fmt.Sprintf(`root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-network:x:100:102:systemd Network Management,,,:/run/systemd:/usr/sbin/nologin
systemd-resolve:x:101:103:systemd Resolver,,,:/run/systemd:/usr/sbin/nologin
messagebus:x:102:105::/nonexistent:/usr/sbin/nologin
systemd-timesync:x:103:106:systemd Time Synchronization,,,:/run/systemd:/usr/sbin/nologin
syslog:x:104:111::/home/syslog:/usr/sbin/nologin
_apt:x:105:65534::/nonexistent:/usr/sbin/nologin
sshd:x:106:65534::/run/sshd:/usr/sbin/nologin
%s:x:1000:1000:%s,,,:/home/%s:/bin/bash
`, s.Username, s.Username, s.Username))

	writeFile(s, "/etc/shadow", fmt.Sprintf(`root:$y$j9T$SALT1234567890$HASHHASHHASHHASHHASH1234567890ABCDEF:19700:0:99999:7:::
daemon:*:19700:0:99999:7:::
bin:*:19700:0:99999:7:::
sys:*:19700:0:99999:7:::
sync:*:19700:0:99999:7:::
nobody:*:19700:0:99999:7:::
sshd:*:19700:0:99999:7:::
%s:$y$j9T$SALTSALTSALT$HASHHASHHASHHASHHASHHASHHASHHASH:19700:0:99999:7:::
`, s.Username))

	writeFile(s, "/etc/group", fmt.Sprintf(`root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:syslog,%s
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:%s
floppy:x:25:
tape:x:26:
sudo:x:27:%s
www-data:x:33:
staff:x:50:
users:x:100:
nogroup:x:65534:
systemd-journal:x:101:
systemd-network:x:102:
systemd-resolve:x:103:
crontab:x:104:
syslog:x:111:
ssh:x:112:
%s:x:1000:
`, s.Username, s.Username, s.Username, s.Username))

	writeFile(s, "/etc/hosts", fmt.Sprintf(`127.0.0.1	localhost
127.0.1.1	%s
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
`, s.Hostname))

	writeFile(s, "/etc/resolv.conf", `# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
search localdomain
`)

	writeFile(s, "/etc/fstab", `# /etc/fstab: static file system information.
UUID=a1b2c3d4-e5f6-7890-abcd-1234567890ab /               ext4    errors=remount-ro 0       1
UUID=d4c3b2a1-f6e5-0987-dcba-ba0987654321 /boot           ext4    defaults          0       2
UUID=11223344-5566-7788-99aa-bbccddeeff00 none            swap    sw                0       0
`)

	writeFile(s, "/etc/crontab", `SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user	command
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
`)

	writeFile(s, "/etc/ssh/sshd_config", `# OpenBSD Secure Shell server configuration
Port 22
AddressFamily any
ListenAddress 0.0.0.0
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
PermitRootLogin prohibit-password
PubkeyAuthentication yes
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem	sftp	/usr/lib/openssh/sftp-server
`)

	writeFile(s, "/etc/apt/sources.list", `deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
`)

	writeFile(s, "/etc/environment", `PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
`)

	writeFile(s, "/etc/timezone", "Etc/UTC\n")

	// ─── /proc ───────────────────────────────────────────────────────
	writeFile(s, "/proc/version", "Linux version 5.15.0-91-generic (buildd@lcy02-amd64-045) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023\n")

	cores := 2 + rand.Intn(14)
	var cpuBuf string
	ghzBase := 2.0 + float64(rand.Intn(20))/10.0
	models := []string{
		"Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz",
		"Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz",
		"AMD EPYC 7R13 48-Core Processor",
		"Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz",
		"AMD Ryzen 9 5950X 16-Core Processor",
	}
	model := models[rand.Intn(len(models))]
	for i := 0; i < cores; i++ {
		cpuBuf += fmt.Sprintf(`processor	: %d
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: %s
stepping	: 7
cpu MHz		: %.3f
cache size	: 36608 KB
physical id	: 0
siblings	: %d
core id		: %d
cpu cores	: %d
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
bogomips	: %.2f
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual

`, i, model, ghzBase*1000+float64(rand.Intn(100)),
			cores, i, cores, ghzBase*2000)
	}
	writeFile(s, "/proc/cpuinfo", cpuBuf)

	memTotal := (4 + rand.Intn(60)) * 1024 * 1024 // 4-64GB in kB
	memFree := memTotal * (20 + rand.Intn(60)) / 100
	writeFile(s, "/proc/meminfo", fmt.Sprintf(`MemTotal:       %d kB
MemFree:        %d kB
MemAvailable:   %d kB
Buffers:        %d kB
Cached:         %d kB
SwapCached:     0 kB
Active:         %d kB
Inactive:       %d kB
SwapTotal:      %d kB
SwapFree:       %d kB
Dirty:          %d kB
`, memTotal, memFree, memFree+memTotal/10,
		rand.Intn(500000), rand.Intn(2000000),
		memTotal/3, memTotal/4,
		memTotal/2, memTotal/2,
		rand.Intn(1000)))

	writeFile(s, "/proc/self/status", fmt.Sprintf(`Name:	%s
Umask:	0022
State:	S (sleeping)
Tgid:	%d
Pid:	%d
PPid:	1
TracerPid:	0
Uid:	%s	%s	%s	%s
Gid:	%s	%s	%s	%s
FDSize:	256
VmPeak:	  %d kB
VmSize:	  %d kB
VmRSS:	  %d kB
Threads:	%d
`, "agent", s.Pid, s.Pid, s.Uid, s.Uid, s.Uid, s.Uid, s.Gid, s.Gid, s.Gid, s.Gid,
		50000+rand.Intn(200000), 40000+rand.Intn(150000), 10000+rand.Intn(50000), 1+rand.Intn(16)))

	writeFile(s, "/proc/uptime", fmt.Sprintf("%d.%02d %d.%02d\n",
		86400+rand.Intn(864000), rand.Intn(99),
		86400+rand.Intn(864000), rand.Intn(99)))

	writeFile(s, "/proc/loadavg", fmt.Sprintf("0.%02d 0.%02d 0.%02d %d/%d %d\n",
		rand.Intn(99), rand.Intn(99), rand.Intn(99),
		1+rand.Intn(5), 100+rand.Intn(200), s.Pid+1))

	// ─── /var/log ────────────────────────────────────────────────────
	logBase := now.Add(-time.Duration(rand.Intn(72)) * time.Hour)
	var authBuf string
	for i := 0; i < 30+rand.Intn(50); i++ {
		t := logBase.Add(time.Duration(i*5+rand.Intn(300)) * time.Minute)
		ts := t.Format("Jan  2 15:04:05")
		switch rand.Intn(5) {
		case 0:
			authBuf += fmt.Sprintf("%s %s sshd[%d]: Accepted publickey for %s from %s port %d ssh2: RSA SHA256:%s\n",
				ts, s.Hostname, 1000+rand.Intn(30000), s.Username,
				fmt.Sprintf("10.%d.%d.%d", rand.Intn(255), rand.Intn(255), rand.Intn(254)+1),
				30000+rand.Intn(35000), randomAlphaNum(43))
		case 1:
			authBuf += fmt.Sprintf("%s %s sshd[%d]: Failed password for invalid user admin from %s port %d ssh2\n",
				ts, s.Hostname, 1000+rand.Intn(30000),
				fmt.Sprintf("%d.%d.%d.%d", rand.Intn(255)+1, rand.Intn(255), rand.Intn(255), rand.Intn(254)+1),
				30000+rand.Intn(35000))
		case 2:
			authBuf += fmt.Sprintf("%s %s systemd-logind[%d]: New session %d of user %s.\n",
				ts, s.Hostname, 400+rand.Intn(100), i+1, s.Username)
		case 3:
			authBuf += fmt.Sprintf("%s %s sudo:   %s : TTY=pts/%d ; PWD=/home/%s ; USER=root ; COMMAND=/usr/bin/apt update\n",
				ts, s.Hostname, s.Username, rand.Intn(4), s.Username)
		case 4:
			authBuf += fmt.Sprintf("%s %s CRON[%d]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)\n",
				ts, s.Hostname, 1000+rand.Intn(30000))
		}
	}
	writeFile(s, "/var/log/auth.log", authBuf)

	var syslogBuf string
	for i := 0; i < 20+rand.Intn(30); i++ {
		t := logBase.Add(time.Duration(i*10+rand.Intn(600)) * time.Minute)
		ts := t.Format("Jan  2 15:04:05")
		switch rand.Intn(4) {
		case 0:
			syslogBuf += fmt.Sprintf("%s %s systemd[1]: Started Session %d of User %s.\n", ts, s.Hostname, i+1, s.Username)
		case 1:
			syslogBuf += fmt.Sprintf("%s %s kernel: [%d.%06d] eth0: renamed from veth%s\n", ts, s.Hostname,
				rand.Intn(999999), rand.Intn(999999), randomAlphaNum(7))
		case 2:
			syslogBuf += fmt.Sprintf("%s %s dhclient[%d]: bound to %s -- renewal in %d seconds.\n",
				ts, s.Hostname, rand.Intn(3000), s.IP, 1800+rand.Intn(3600))
		case 3:
			syslogBuf += fmt.Sprintf("%s %s rsyslogd: [origin software=\"rsyslogd\" swVersion=\"8.2112.0\"] rsyslogd was HUPed\n",
				ts, s.Hostname)
		}
	}
	writeFile(s, "/var/log/syslog", syslogBuf)

	writeFile(s, "/var/log/dpkg.log", fmt.Sprintf(`%s upgrade apt:amd64 2.4.10 2.4.11
%s install libssl3:amd64 <none> 3.0.2-0ubuntu1.12
%s configure libssl3:amd64 3.0.2-0ubuntu1.12 <none>
%s upgrade openssl:amd64 3.0.2-0ubuntu1.10 3.0.2-0ubuntu1.12
`, now.Add(-72*time.Hour).Format("2006-01-02 15:04:05"),
		now.Add(-72*time.Hour).Format("2006-01-02 15:04:05"),
		now.Add(-72*time.Hour).Format("2006-01-02 15:04:05"),
		now.Add(-72*time.Hour).Format("2006-01-02 15:04:05")))

	writeFile(s, "/var/log/lastlog", "")
	writeFile(s, "/var/log/wtmp", "")

	// ─── home directories ────────────────────────────────────────────
	home := fmt.Sprintf("/home/%s", s.Username)
	if s.Username == "root" {
		home = "/root"
	}

	writeFile(s, home+"/.bashrc", `# ~/.bashrc: executed by bash(1) for non-login shells.
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
export EDITOR=vim
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
`)

	writeFile(s, home+"/.profile", `# ~/.profile: executed by the command interpreter for login shells.
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
`)

	bashHistory := []string{
		"sudo apt update && sudo apt upgrade -y",
		"systemctl status nginx",
		"tail -f /var/log/syslog",
		"df -h",
		"free -m",
		"top -bn1 | head -20",
		"ps aux | grep python",
		"netstat -tlnp",
		"cat /etc/passwd",
		"ls -la /opt/",
		"journalctl -u ssh --since today",
		"docker ps -a",
		"git pull origin main",
		"vim /etc/nginx/nginx.conf",
		"curl -s https://api.ipify.org",
		"ss -tlnp",
		"uname -a",
		"id",
		"w",
		"uptime",
	}
	var histBuf string
	count := 10 + rand.Intn(len(bashHistory)-10)
	for i := 0; i < count; i++ {
		histBuf += bashHistory[rand.Intn(len(bashHistory))] + "\n"
	}
	writeFile(s, home+"/.bash_history", histBuf)

	writeFile(s, home+"/.ssh/authorized_keys", fmt.Sprintf("ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD%s %s@%s\n",
		randomAlphaNum(368), s.Username, s.Hostname))
	writeFile(s, home+"/.ssh/known_hosts", fmt.Sprintf("github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl\n10.0.0.1 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB%s\n", randomAlphaNum(200)))

	writeFile(s, home+"/Documents/notes.txt", fmt.Sprintf(`Project Notes - %s
===================
- Deploy new API version by Friday
- Review PR #%d for auth module
- Update monitoring dashboards
- Check backup status on db-primary
- TODO: rotate SSH keys for production
`, now.Format("2006-01-02"), 100+rand.Intn(900)))

	writeFile(s, home+"/Documents/todo.md", `# TODO List
- [x] Set up CI/CD pipeline
- [x] Configure monitoring alerts
- [ ] Migrate database to new cluster
- [ ] Update SSL certificates (expires next month)
- [ ] Review security audit findings
`)

	// ─── System binaries (name-only stubs) ───────────────────────────
	binaries := []string{
		"/bin/bash", "/bin/sh", "/bin/ls", "/bin/cat", "/bin/cp",
		"/bin/mv", "/bin/rm", "/bin/mkdir", "/bin/chmod", "/bin/chown",
		"/bin/grep", "/bin/sed", "/bin/awk", "/bin/find", "/bin/tar",
		"/bin/gzip", "/bin/ping", "/bin/hostname", "/bin/uname", "/bin/id",
		"/bin/whoami", "/bin/ps", "/bin/kill", "/bin/mount", "/bin/umount",
		"/usr/bin/vim", "/usr/bin/nano", "/usr/bin/wget", "/usr/bin/curl",
		"/usr/bin/ssh", "/usr/bin/scp", "/usr/bin/git", "/usr/bin/python3",
		"/usr/bin/pip3", "/usr/bin/sudo", "/usr/bin/apt", "/usr/bin/dpkg",
		"/usr/bin/systemctl", "/usr/bin/journalctl", "/usr/bin/top",
		"/usr/bin/htop", "/usr/bin/netstat", "/usr/bin/ss", "/usr/bin/ip",
		"/usr/bin/iptables", "/usr/bin/nmap", "/usr/bin/nc",
		"/usr/sbin/sshd", "/usr/sbin/cron", "/usr/sbin/rsyslogd",
		"/usr/sbin/nginx", "/usr/sbin/apache2",
	}
	for _, b := range binaries {
		size := 50000 + rand.Intn(2000000)
		writeFileWithSize(s, b, size)
	}
}

func randomAlphaNum(n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/"
	b := make([]byte, n)
	for i := range b {
		b[i] = chars[rand.Intn(len(chars))]
	}
	return string(b)
}

func writeFile(s *SessionFS, path, content string) {
	afero.WriteFile(s.Fs, path, []byte(content), 0644)
}

func writeFileWithSize(s *SessionFS, path string, size int) {
	// Create a file with the given size (header + zeros, not truly random—saves CPU)
	header := []byte("#!/bin/sh\n# ELF binary stub\n")
	data := make([]byte, size)
	copy(data, header)
	afero.WriteFile(s.Fs, path, data, 0755)
}
